### ISSUE TITLE
Confirm issue

### ISSUE THREAD

**Issue by ghost** [Duerocraft/AternosAPI#1]
How did you tackle the issue to confirm you are still there so the server can start? It's a popup notification that gets sent thru

**Comment by ghost** [comment]
Update I figured out the URL for the confirm but getting a 412 preconditioned not met error when sending a request

**Comment by Aur0raN** [comment]
Have you fixed the issue for that cause I cant figure it out either

**Comment by ghost** [comment]
@Aur0raN haven't given it much attempt since the last comment I made. Will try to pick up again today maybe. Will keep posted here till we get a response from @Duerocraft Mohanavel when he has a chance.

**Comment by Duerocraft** [comment]
hi, i will try to find a way to get around it. Join my discord server i will mostly active on my discord server : discord.gg/VCGWz8w

**Comment by Duerocraft** [comment]
hi, updated the code. now it automatically wait & skip the queue
