### ISSUE TITLE
'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by hackermen0** [Duerocraft/AternosAPI#10]
![image](https://user-images.githubusercontent.com/82448251/114543707-2e7e4300-9c77-11eb-9464-469a5ba17fa2.png)
I gave my header_cookie and my token 
and when i run the code it doens't give me any error
But if i do anything like asking the info or starting server it gives me this error

Note: Im running this off the example file provided

**Comment by Matias-source** [comment]
I fixed it using cloudscraper instead of requests.

https://github.com/Matias-source/AternosAPI

**Comment by hackermen0** [comment]
Thanks a lot, I will check it out later
